version: "3.9"

services:
  mongo:
    image: mongo
    container_name: feedback_mongo
    ports:
      - "27017:27017"
    command: mongod --noauth
    volumes:
      - mongo_data:/data/db
  
  backend:
    build: .
    container_name: feedback_backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - DATABASE_NAME=feedback_db
    depends_on:
      - mongo

volumes:
  mongo_data: